// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Graphql = require("graphql");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

var Language = /* module */[];

var $$Error = /* module */[];

var Type = /* module */[];

var Execution = /* module */[];

var Utilities = /* module */[];

var Validation = /* module */[];

function run(rootValue, contextValue, variableValue, operationName, fieldResolver, schema, source, param) {
  return Graphql.graphql({
              schema: schema,
              source: source,
              rootValue: Js_null_undefined.fromOption(rootValue),
              contextValue: Js_null_undefined.fromOption(contextValue),
              variableValue: Js_null_undefined.fromOption(variableValue),
              operationName: Js_null_undefined.fromOption(operationName),
              fieldResolver: Js_null_undefined.fromOption(fieldResolver)
            });
}

exports.Language = Language;
exports.$$Error = $$Error;
exports.Type = Type;
exports.Execution = Execution;
exports.Utilities = Utilities;
exports.Validation = Validation;
exports.run = run;
/* graphql Not a pure module */
